name: Request.Keywords
author: thinkphp
current: v1.0  
category: Request  
tags: [request,keywords,boss,yahoo]
docs: http://github.com/thinkphp/Request.Keywords/blob/master/Docs/Request.Keywords.md
demo:  
